name: Build Mojing AI OS - Commercial Ultra

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          
      - run: |
          # 强行指定底层的合法包名，绕过 GitHub 仓库名的横杠限制
          flutter create . --project-name mojing_ai_os --platforms android
          flutter pub get
          flutter build apk --release
          
      - uses: actions/upload-artifact@v4
        with:
          name: 墨境AI_全息视觉商用版_APK
          path: build/app/outputs/flutter-apk/app-release.apk
